In [1]:
import open_clip
open_clip.list_pretrained()

[('RN50', 'openai'),
 ('RN50', 'yfcc15m'),
 ('RN50', 'cc12m'),
 ('RN50-quickgelu', 'openai'),
 ('RN50-quickgelu', 'yfcc15m'),
 ('RN50-quickgelu', 'cc12m'),
 ('RN101', 'openai'),
 ('RN101', 'yfcc15m'),
 ('RN101-quickgelu', 'openai'),
 ('RN101-quickgelu', 'yfcc15m'),
 ('RN50x4', 'openai'),
 ('RN50x16', 'openai'),
 ('RN50x64', 'openai'),
 ('ViT-B-32', 'openai'),
 ('ViT-B-32', 'laion400m_e31'),
 ('ViT-B-32', 'laion400m_e32'),
 ('ViT-B-32', 'laion2b_e16'),
 ('ViT-B-32', 'laion2b_s34b_b79k'),
 ('ViT-B-32', 'datacomp_xl_s13b_b90k'),
 ('ViT-B-32', 'datacomp_m_s128m_b4k'),
 ('ViT-B-32', 'commonpool_m_clip_s128m_b4k'),
 ('ViT-B-32', 'commonpool_m_laion_s128m_b4k'),
 ('ViT-B-32', 'commonpool_m_image_s128m_b4k'),
 ('ViT-B-32', 'commonpool_m_text_s128m_b4k'),
 ('ViT-B-32', 'commonpool_m_basic_s128m_b4k'),
 ('ViT-B-32', 'commonpool_m_s128m_b4k'),
 ('ViT-B-32', 'datacomp_s_s13m_b4k'),
 ('ViT-B-32', 'commonpool_s_clip_s13m_b4k'),
 ('ViT-B-32', 'commonpool_s_laion_s13m_b4k'),
 ('ViT-B-32', 'commonpool_

In [15]:
a=[1,2,3]
b=[4,5,6]
b.extend(a)
print(b)

[4, 5, 6, 1, 2, 3]


In [26]:
import webdataset as wds
import torch
import io
from torch.nn.functional import cosine_similarity
dataset = wds.WebDataset("/home/user/data/cc12m_dr/00000.tar")
for sample in dataset:
    print(sample['paug.json'].decode('utf-8'))
    print(sample["syn_caps.json"].decode('utf-8'))
    print(sample["txt"].decode('utf-8'))
    buffer = io.BytesIO(sample['pth'])
    tensor = torch.load(buffer)
    print(tensor)
    print(cosine_similarity(tensor['text_emb'][2].unsqueeze(0),tensor['text_emb'][3].unsqueeze(0)))
    print(cosine_similarity(tensor['image_emb'][1].unsqueeze(0),tensor['image_emb'][3].unsqueeze(0)))
    break

[[[8, 36, 226, 207], [[3, 30.45317268371582], [8, -0.26999998092651367]]], [[152, 29, 102, 93], [[3, -30.45317268371582], [13, 0.0]]], [[81, 9, 134, 117], [[6, 0.26999998092651367], [4, -30.45317268371582]]], [[85, 18, 85, 84], [[9, 0.26999998092651367], [13, 0.0]]], [[9, 3, 236, 251], [[10, 7.0], [5, -9.0]]]]
["a man is holding a green object and a quote ", "a man holding a ball with a quote about it . ", "a man holding a tennis ball in a field . "]
The source of Anime quotes & Manga quotes : Photo <PERSON>, Manga Quotes, Art Images, Fan Art, Thoughts, Think, Anime, Crying, Random
{'image_emb': [tensor([ 1.1406, -0.1748,  0.2490,  ..., -1.0547,  1.8984,  0.5781],
       dtype=torch.bfloat16), tensor([ 0.6719, -0.1592, -1.0938,  ..., -0.9453,  1.4688,  0.8438],
       dtype=torch.bfloat16), tensor([ 0.7617,  0.1162, -0.6523,  ..., -0.5195,  1.6172,  0.5234],
       dtype=torch.bfloat16), tensor([ 0.2090,  0.1826, -0.2266,  ..., -0.3730,  3.7656,  0.2988],
       dtype=torch.bfloat16), 

In [27]:
import webdataset as wds
import torch
import io
from torch.nn.functional import cosine_similarity
dataset = wds.WebDataset("/home/user/data/cc12m_fixsyn_dr/00000.tar")
for sample in dataset:
    print(sample['paug.json'].decode('utf-8'))
    print(sample["syn_caps.json"].decode('utf-8'))
    print(sample["txt"].decode('utf-8'))
    buffer = io.BytesIO(sample['pth'])
    tensor = torch.load(buffer)
    print(tensor)
    print(cosine_similarity(tensor['text_emb'][2].unsqueeze(0),tensor['text_emb'][3].unsqueeze(0)))
    print(cosine_similarity(tensor['image_emb'][1].unsqueeze(0),tensor['image_emb'][3].unsqueeze(0)))
    break

[[[8, 36, 226, 207], [[3, 30.45317268371582], [8, -0.26999998092651367]]], [[152, 29, 102, 93], [[3, -30.45317268371582], [13, 0.0]]], [[81, 9, 134, 117], [[6, 0.26999998092651367], [4, -30.45317268371582]]], [[85, 18, 85, 84], [[9, 0.26999998092651367], [13, 0.0]]], [[9, 3, 236, 251], [[10, 7.0], [5, -9.0]]]]
["a man is holding a green object and a quote ", "a man holding a ball with a quote about it . ", "a man holding a tennis ball in a field . "]
The source of Anime quotes & Manga quotes : Photo <PERSON>, Manga Quotes, Art Images, Fan Art, Thoughts, Think, Anime, Crying, Random
{'image_emb': [tensor([ 1.1406, -0.1748,  0.2490,  ..., -1.0547,  1.8984,  0.5781],
       dtype=torch.bfloat16), tensor([ 0.6719, -0.1592, -1.0938,  ..., -0.9453,  1.4688,  0.8438],
       dtype=torch.bfloat16), tensor([ 0.7617,  0.1162, -0.6523,  ..., -0.5195,  1.6172,  0.5234],
       dtype=torch.bfloat16), tensor([ 0.2090,  0.1826, -0.2266,  ..., -0.3730,  3.7656,  0.2988],
       dtype=torch.bfloat16), 

In [1]:
import torch
tensor = torch.load('/home/user/data/cc12m_dr/01000/010000001.pth')

In [2]:
tensor

{'image_emb': [tensor([ 0.5820,  0.8750, -0.3301,  ..., -0.0483, -2.2031,  1.0078],
         dtype=torch.bfloat16),
  tensor([ 0.2734,  1.2500,  0.1289,  ...,  0.0327, -1.1406,  0.8008],
         dtype=torch.bfloat16),
  tensor([-0.0864,  0.4375,  0.0598,  ..., -0.3867, -2.2344,  0.4355],
         dtype=torch.bfloat16),
  tensor([ 0.4707,  1.0781, -0.1455,  ..., -0.0806, -2.2500,  1.0781],
         dtype=torch.bfloat16),
  tensor([ 0.2676,  0.6055, -0.0618,  ...,  0.0354,  0.1963,  0.3945],
         dtype=torch.bfloat16)],
 'text_emb': [tensor([-0.5234,  0.1318, -0.6914,  ...,  0.0015, -0.3594,  0.5117],
         dtype=torch.bfloat16),
  tensor([-0.3516,  0.4219,  0.5117,  ...,  0.3438,  0.0796,  0.9102],
         dtype=torch.bfloat16),
  tensor([-0.7812, -0.2852,  0.0025,  ..., -0.8047,  0.6875,  0.0942],
         dtype=torch.bfloat16),
  tensor([-0.3145,  0.0688, -0.0688,  ..., -0.5000,  1.1562, -0.0942],
         dtype=torch.bfloat16)]}

In [3]:
len(tensor['image_emb'])

5

In [4]:
tensor['image_emb'][0].shape

torch.Size([1536])

In [5]:
len(tensor['text_emb'])

4

In [6]:
tensor['text_emb'][0].shape

torch.Size([1536])

In [1]:
import json
with open('/home/user/data/DataCompDR/DataCompDR-12M-bf16/00000000/5252820736bc680b29c6dca972776dc3.paug.json','r') as f:
    dic = json.load(f)
    

In [2]:
print(len(dic['param_aug']))

30


In [3]:
print(len(dic['param_aug'][0]))

2


In [4]:
print(dic['param_aug'][0])

[[33, 29, 48, 57], [[13, 0.0], [11, 178.5]]]


In [14]:
import gzip
import torch

with gzip.open('/home/user/data/DataCompDR/DataCompDR-12M-bf16/00000000/5252820736bc680b29c6dca972776dc3.pth.gz', 'rb') as f:
    tensor = torch.load(f)

In [15]:
print(len(tensor['text_emb']))

7


In [7]:
print(tensor['text_emb'][0].shape)

torch.Size([1536])


In [8]:
print(tensor['image_emb'][0].shape)

torch.Size([1536])


In [9]:
tensor['text_emb']

tensor([[ 0.0037, -0.0552, -0.0244,  ..., -0.0537, -0.0037,  0.0378],
        [ 0.0037, -0.0552, -0.0244,  ..., -0.0537, -0.0037,  0.0378],
        [ 0.0408, -0.0261,  0.0214,  ..., -0.0776, -0.0013, -0.0064],
        ...,
        [-0.0272, -0.0254,  0.0016,  ..., -0.0479,  0.0339,  0.0535],
        [-0.0109,  0.0195,  0.0005,  ..., -0.0520, -0.0298,  0.0072],
        [-0.0186, -0.0315, -0.0067,  ..., -0.0737,  0.0508,  0.0366]],
       dtype=torch.bfloat16)

In [10]:
tensor['text_emb'][0]

tensor([ 0.0037, -0.0552, -0.0244,  ..., -0.0537, -0.0037,  0.0378],
       dtype=torch.bfloat16)

In [11]:
tensor['text_emb'][1]

tensor([ 0.0037, -0.0552, -0.0244,  ..., -0.0537, -0.0037,  0.0378],
       dtype=torch.bfloat16)

In [12]:
tensor['text_emb'][2]

tensor([ 0.0408, -0.0261,  0.0214,  ..., -0.0776, -0.0013, -0.0064],
       dtype=torch.bfloat16)

In [13]:
tensor['text_emb'][0] == tensor['text_emb'][1]

tensor([True, True, True,  ..., True, True, True])

In [14]:
for i in (tensor['text_emb'][0] == tensor['text_emb'][1]):
    if i == True:
        continue
    else:
        print(False)
        break

In [15]:
torch.sum(tensor['text_emb'][0])

tensor(0.5859, dtype=torch.bfloat16)

In [16]:
torch.norm(torch.nn.functional.normalize(tensor['text_emb'][0],dim=-1))

tensor(1., dtype=torch.bfloat16)